### ISSUE TITLE
Secret `propagator-webhook-server-cert` not found since `v0.11.0`

### ISSUE THREAD

**Issue by yanmxa** [open-cluster-management-io/governance-policy-propagator#226]
I try to deploy the propagator by applying the resource: https://raw.githubusercontent.com/open-cluster-management-io/governance-policy-framework-addon/v0.12.0/deploy/operator.yaml. But the pod keeps showing `ContainerCreating`
```bash
open-cluster-management               cluster-manager-5744d5fc8-56dvr                            1/1     Running             0          35m
open-cluster-management               governance-policy-propagator-7444b4b958-6524b              0/1     ContainerCreating   0          30m
open-cluster-management               governance-policy-propagator-78dccd9b9f-v5qhq              0/1     ContainerCreating   0          30m
```bsh
It was later discovered that the issue was caused by the secret `propagator-webhook-server-cert` not being created.
```bash
oc describe pod governance-policy-propagator-78dccd9b9f-v5qhq -n open-cluster-management
 ...
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                 From               Message
  ----     ------       ----                ----               -------
  Normal   Scheduled    38m                 default-scheduler  Successfully assigned open-cluster-management/governance-policy-propagator-78dccd9b9f-v5qhq to hub1-control-plane
  Warning  FailedMount  87s (x26 over 38m)  kubelet            MountVolume.SetUp failed for volume "cert" : secret "propagator-webhook-server-cert" not found
```

I checked the code, and it seems we have never created this secret?

**Comment by dhaiducek** [comment]
This is expected since we added a webhook and require a certificate for it. You can either:
- Disable the webhook with the `--enable-webhooks=false` argument for the controller
- Deploy `cert-manager` and apply [deploy/webhook.yaml](https://github.com/open-cluster-management-io/governance-policy-propagator/blob/main/deploy/webhook.yaml) (this can be done with the `make webhook` command):
  https://github.com/open-cluster-management-io/governance-policy-propagator/blob/391897060b115e35b7d4faa247764bc91079711d/Makefile#L175-L177

**Comment by dhaiducek** [comment]
Since you're deploying upstream code, you could alternatively use `clusteradm` to deploy the propagator, which we make an effort to keep up-to-date and has the webhook disabled by default.

**Comment by yanmxa** [comment]
Thanks @dhaiducek! I follow the [document](https://open-cluster-management.io/getting-started/integration/policy-framework/) to install the controller from the source. It seems the document hasn't mentioned it. So I pull a request to modify it, please take a look~
